// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhbsoyxl3S6_k_35CUMZl9fa1wKBztN-4',
    appId: '1:956406982456:web:bc14ff8bc100b5c027c3cd',
    messagingSenderId: '956406982456',
    projectId: 'mysigin-fc38a',
    authDomain: 'mysigin-fc38a.firebaseapp.com',
    storageBucket: 'mysigin-fc38a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzmzNkxGXd9CXIqkQkYlhIMIHKnu0BTzg',
    appId: '1:956406982456:android:ed53bcdc79ffa8e127c3cd',
    messagingSenderId: '956406982456',
    projectId: 'mysigin-fc38a',
    storageBucket: 'mysigin-fc38a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMuzGXLYFKrlExzXJ5NQ4x9z0YYxREgNI',
    appId: '1:956406982456:ios:dc7e83692743e47d27c3cd',
    messagingSenderId: '956406982456',
    projectId: 'mysigin-fc38a',
    storageBucket: 'mysigin-fc38a.appspot.com',
    iosClientId: '956406982456-smgra0mstm4eas84kqfp64k9keje8v5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.signinApp',
  );
}
